module.exports = [
  {
    isBox: true,
    slug: "box-presidente-sumatra",
    name: "Presidente Sumatra",
    title: "Presidente Sumatra Box | Pita Cigars",
    description: "Flor de Pita Presidente Sumatra: a hand-rolled Nicaraguan presidente with a Sumatra-shade wrapper, sold in boxes of 25 by Pita Cigars.",
    blend: "Sumatra Shade Wrapper",
    price: "$100.00",
    quantity: 25,
    strength: 3,
    strengthLabel: "Medium",
    desc: "When you&rsquo;re ready to upgrade your smoke to the highest quality, you&rsquo;re going to want to get your hands on our Presidente. The only problem will be getting your hands off it. A golden Sumatra-shade wrapper over aged Nicaraguan long-filler lets you indulge in the luxury of a premium smoke without compromising on quality, and every box holds twenty-five of them.",
    ogImage: "/assets/images/box-presidente-sumatra.svg",
    images: [
      { src: "/assets/images/box-presidente-sumatra.svg", alt: "Flor de Pita Presidente Sumatra, box of 25", width: 720, height: 960 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Presidente &middot; 7&#189;&quot; x 50" },
      { label: "Quantity", value: "25 Cigars" },
      { label: "Wrapper", value: "Sumatra Shade" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Jalapa)" },
    ],
    notes: ["Cedar", "Cream", "Sweet Spice", "Almond", "Coffee"],
    storyHeading: "The Flagship Format",
    story: [
      "At seven and a half inches with a 50 ring gauge, the Presidente is the longest, most unhurried cigar we roll. The Sumatra-seed wrapper brings a restrained natural sweetness and delicate spice to our aged Nicaraguan core, and the extended format gives the blend room to unfold over a full evening.",
      "Each box of twenty-five leaves the aging room together, rolled from the same harvest and rested side by side, so the last cigar in the box smokes exactly like the first.",
    ],
    related: ["box-presidente-indonesian"],
  },
  {
    isBox: true,
    slug: "box-presidente-indonesian",
    name: "Presidente Indonesian",
    title: "Presidente Indonesian Box | Pita Cigars",
    description: "Flor de Pita Presidente Indonesian: a hand-rolled Nicaraguan presidente with a dark Indonesian wrapper, sold in boxes of 25 by Pita Cigars.",
    blend: "Indonesian Wrapper",
    price: "$100.00",
    quantity: 25,
    strength: 5,
    strengthLabel: "Full",
    desc: "Our Presidente Indonesian is one of our highest quality dark-wrapped cigars. This long-filler cigar will give you the smoke you&rsquo;re looking for: deep earth, dark cocoa, and a long, rounded finish. Our box sets come with twenty-five of the best Indonesian-wrapped presidentes you will find.",
    ogImage: "/assets/images/box-presidente-indonesian.jpg",
    images: [
      { src: "/assets/images/box-presidente-indonesian.webp", alt: "Flor de Pita Presidente Indonesian: Presidente Selects box of 25 with blue ribbon", width: 928, height: 1104 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Presidente &middot; 7&#189;&quot; x 50" },
      { label: "Quantity", value: "25 Cigars" },
      { label: "Wrapper", value: "Indonesian" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Jalapa)" },
    ],
    notes: ["Earth", "Dark Cocoa", "Espresso", "Molasses", "Leather"],
    storyHeading: "Darkness, Refined",
    story: [
      "The Presidente Indonesian pairs our aged Nicaraguan core with a rich, dark Indonesian-grown wrapper leaf. It is the deepest expression of the blend we make: earth and dark cocoa up front, a slow sweetness underneath, and a finish that rewards patience across all seven and a half inches.",
      "Twenty-five to a box, aged together and boxed together, it is the cigar we set aside for the nights that deserve more than an hour.",
    ],
    related: ["box-presidente-sumatra", "box-robusto-indonesian"],
  },
  {
    isBox: true,
    slug: "box-robusto-sumatra",
    name: "Robusto Sumatra",
    title: "Robusto Sumatra Box | Pita Cigars",
    description: "Flor de Pita Robusto Sumatra: a hand-rolled Nicaraguan robusto with a Sumatra-shade wrapper, sold in boxes of 25 by Pita Cigars.",
    blend: "Sumatra Shade Wrapper",
    price: "$90.00",
    quantity: 25,
    strength: 3,
    strengthLabel: "Medium",
    desc: "The stout, slow-burning robusto our regulars reach for, dressed in a genuine Sumatra-shade wrapper and stacked twenty-five deep. Subtly sweet, gently spiced, and effortlessly smooth, this is a full box of the everyday hour.",
    ogImage: "/assets/images/box-robusto-sumatra.jpg",
    images: [
      { src: "/assets/images/box-robusto-sumatra.webp", alt: "Flor de Pita Robusto Sumatra: five hand-rolled robustos with the Flor de Pita band", width: 960, height: 1072 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Robusto &middot; 5&quot; x 52" },
      { label: "Quantity", value: "25 Cigars" },
      { label: "Wrapper", value: "Sumatra Shade" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Jalapa)" },
    ],
    notes: ["Sweet Spice", "Cedar", "Toasted Bread", "Raisin", "Coffee"],
    storyHeading: "The Everyday Hour, By the Box",
    story: [
      "The Robusto Sumatra pairs our aged Nicaraguan core with a Sumatra-seed wrapper leaf prized for its restrained natural sweetness and delicate spice. At five inches with a 52 ring gauge, it is the most companionable cigar we make.",
      "By the box, it becomes a habit worth keeping: twenty-five cigars from the same rolling table, resting in cedar until the day you reach for the next one.",
    ],
    related: ["box-robusto-indonesian"],
  },
  {
    isBox: true,
    slug: "box-robusto-indonesian",
    name: "Robusto Indonesian",
    title: "Robusto Indonesian Box | Pita Cigars",
    description: "Flor de Pita Robusto Indonesian: a hand-rolled Nicaraguan robusto with a dark Indonesian wrapper, sold in boxes of 25 by Pita Cigars.",
    blend: "Indonesian Wrapper",
    price: "$90.00",
    quantity: 25,
    strength: 5,
    strengthLabel: "Full",
    desc: "The Robusto Sumatra&rsquo;s darker sibling, by the box: a rich Indonesian-grown wrapper laid over our aged Nicaraguan long-filler core, twenty-five to a box. Deeper earth, dark cocoa, and a rounded, medium-bodied finish from the first draw to the last.",
    ogImage: "/assets/images/box-robusto-indonesian.jpg",
    images: [
      { src: "/assets/images/box-robusto-indonesian.webp", alt: "Flor de Pita Robusto Indonesian: five hand-rolled robustos with the Flor de Pita band", width: 1008, height: 1024 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Robusto &middot; 5&quot; x 52" },
      { label: "Quantity", value: "25 Cigars" },
      { label: "Wrapper", value: "Indonesian" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Jalapa)" },
    ],
    notes: ["Earth", "Dark Cocoa", "Oak", "Molasses", "Black Pepper"],
    storyHeading: "A Darker Shade of Familiar",
    story: [
      "The Robusto Indonesian takes the format our regulars know best and deepens it: a dark Indonesian-grown wrapper over the same aged Est&eacute;l&iacute; and Jalapa filler, trading the Sumatra&rsquo;s sweetness for earth, oak, and dark cocoa.",
      "Boxed in twenty-fives, it is built for the shelf you actually smoke from, medium-bodied, consistent, and never precious about the occasion.",
    ],
    related: ["box-robusto-sumatra"],
  },
];
