module.exports = [
  {
    slug: "torpedo-habano",
    name: "Torpedo Habano",
    title: "Torpedo Habano | Pita Cigars",
    description: "Torpedo Habano, hand-rolled Nicaraguan cigar with a Habano Shade wrapper, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Habano Shade Wrapper",
    price: "$40.00",
    quantity: 25,
    strength: 4,
    strengthLabel: "Full",
    desc: "Hand-rolled in Nicaragua with an aged Nicaraguan filler beneath a dark, oily Habano Shade wrapper, this bold torpedo delivers a rich, full-bodied smoke. Its tapered head concentrates the draw for layered notes of espresso and cocoa over a foundation of pepper and aged cedar. A Nicaraguan puro built for the seasoned palate.",
    ogImage: "/assets/images/premium-torpedo-habano.jpg",
    images: [
      { src: "/assets/images/premium-torpedo-habano.webp", alt: "Torpedo Habano spec card: Nicaraguan filler and binder, Habano Shade wrapper, vitola 6 x 52", width: 720, height: 1280 },
      { src: "/assets/images/premium-torpedo-habano-bundle.webp", alt: "Torpedo Habano bundle of 25 banded 6 x 52", width: 832, height: 1248 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Torpedo &middot; 6.1&quot; x 52" },
      { label: "Quantity", value: "25 per Bundle" },
      { label: "Wrapper", value: "Habano Shade" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute;)" },
    ],
    notes: ["Espresso", "Dark Cocoa", "Black Pepper", "Cedar", "Leather"],
    story: [
      "The Torpedo Habano earns its name from the figurado shape our rollers hand-form leaf by leaf, a tapered head that concentrates the aromas of a sun-grown Habano Shade wrapper into every draw.",
      "Wrapper, binder, and filler are all grown in the volcanic soil of Est&eacute;l&iacute;, making this a true Nicaraguan puro. Slow-fermented and patiently aged, it delivers depth and power without ever losing its balance.",
    ],
    related: ["torpedo-connecticut", "toro-habano"],
  },
  {
    slug: "torpedo-connecticut",
    name: "Torpedo Connecticut",
    title: "Torpedo Connecticut | Pita Cigars",
    description: "Torpedo Connecticut, hand-rolled Nicaraguan Connecticut cigar, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Connecticut Shade Wrapper",
    price: "$40.00",
    quantity: 25,
    strength: 2,
    strengthLabel: "Mild &ndash; Medium",
    desc: "Hand-rolled in Nicaragua with an aged Nicaraguan filler beneath a silky Connecticut-shade wrapper, this elegant torpedo delivers a smooth, full-flavored smoke with a gentle sweetness and a tapered head that sharpens every note. The perfect morning cigar and an ideal introduction to the Pita house style.",
    ogImage: "/assets/images/premium-torpedo-connecticut.jpg",
    images: [
      { src: "/assets/images/premium-torpedo-connecticut.webp", alt: "Torpedo Connecticut spec card: Nicaraguan filler and binder, Connecticut shade wrapper, vitola 6 x 52", width: 720, height: 1280 },
      { src: "/assets/images/premium-torpedo-connecticut-bundle.webp", alt: "Torpedo Connecticut bundle of 25 banded 6 x 52", width: 832, height: 1248 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Torpedo &middot; 6&quot; x 52" },
      { label: "Quantity", value: "25 per Bundle" },
      { label: "Wrapper", value: "Connecticut Shade" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute;)" },
    ],
    notes: ["Cream", "Cedar", "Almond", "Sweet Hay", "White Pepper"],
    story: [
      "The Torpedo Connecticut pairs our signature figurado shape with a shade-grown Connecticut wrapper, prized for its supple texture and naturally sweet, understated flavor.",
      "Beneath that golden leaf sits a core of aged Nicaraguan long-filler, hand-bunched to burn slow and cool. Refined without being timid, it proves a milder cigar need never be a lesser one.",
    ],
    related: ["torpedo-habano", "robusto-sumatra"],
  },
  {
    slug: "robusto-sumatra",
    name: "Robusto Sumatra",
    title: "Robusto Sumatra | Pita Cigars",
    description: "Robusto Sumatra, hand-rolled Nicaraguan robusto with a Sumatra-shade wrapper, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Sumatra Shade Wrapper",
    price: "$40.00",
    quantity: 25,
    strength: 2,
    strengthLabel: "Mild &ndash; Medium",
    desc: "A stout, slow-burning robusto dressed in a genuine Sumatra-shade wrapper, subtly sweet, gently spiced, and effortlessly smooth. The same aged Nicaraguan long-filler as our torpedoes in a shorter format, built for the everyday hour.",
    ogImage: "/assets/images/premium-robusto-sumatra.jpg",
    images: [
      { src: "/assets/images/premium-robusto-sumatra.webp", alt: "Robusto Sumatra spec card: Nicaraguan filler and binder, Sumatra shade wrapper, vitola 5 x 50", width: 720, height: 1280 },
      { src: "/assets/images/premium-robusto-sumatra-bundle.webp", alt: "Robusto Sumatra bundle of 25 with a single cigar resting against it", width: 768, height: 1024 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Robusto &middot; 5&quot; x 50" },
      { label: "Quantity", value: "25 per Bundle" },
      { label: "Wrapper", value: "Sumatra Shade" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute;)" },
    ],
    notes: ["Sweet Spice", "Cedar", "Toasted Bread", "Raisin", "Coffee"],
    story: [
      "The Robusto Sumatra pairs our aged Nicaraguan core with a Sumatra-seed wrapper leaf prized for its restrained natural sweetness and delicate spice.",
      "At five inches with a 50 ring gauge, it is the most companionable cigar we make: forty-five unhurried minutes of sweet earth, cedar, and soft baking spice that never asks more of you than it gives.",
    ],
    related: ["robusto-indonesian", "torpedo-habano"],
  },
  {
    slug: "robusto-indonesian",
    name: "Robusto Indonesian",
    title: "Robusto Indonesian | Pita Cigars",
    description: "Robusto Indonesian, hand-rolled Nicaraguan robusto with a dark Indonesian wrapper, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Indonesian Wrapper",
    price: "$40.00",
    quantity: 25,
    strength: 3,
    strengthLabel: "Medium",
    desc: "The Robusto Sumatra&rsquo;s darker sibling, a rich Indonesian-grown wrapper laid over the same aged Nicaraguan long-filler core. Deeper earth, dark cocoa, and a rounded, medium-bodied finish from the first draw to the last.",
    ogImage: "/assets/images/premium-robusto-indonesian.jpg",
    images: [
      { src: "/assets/images/premium-robusto-indonesian.webp", alt: "Robusto Indonesian spec card: Indonesian filler and binder, Indonesian shade wrapper, vitola 5 x 50", width: 720, height: 1280 },
      { src: "/assets/images/premium-robusto-indonesian-bundle.webp", alt: "Robusto Indonesian bundle with a single cigar resting against it", width: 768, height: 1024 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Robusto &middot; 5&quot; x 50" },
      { label: "Quantity", value: "25 per Bundle" },
      { label: "Wrapper", value: "Indonesian" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute;)" },
    ],
    notes: ["Earth", "Dark Cocoa", "Oak", "Molasses", "Black Pepper"],
    story: [
      "The Robusto Indonesian drapes our Nicaraguan long-filler in an Indonesian-grown wrapper, a darker, oilier leaf that trades the Sumatra&rsquo;s sweetness for depth.",
      "Expect a fuller, earthier smoke with notes of dark cocoa and seasoned oak, balanced so the strength builds gently rather than announcing itself. The same blend beneath, an entirely different evening.",
    ],
    related: ["robusto-sumatra", "toro-habano"],
  },
  {
    slug: "churchill-sumatra",
    name: "Churchill Sumatra",
    title: "Churchill Sumatra | Pita Cigars",
    description: "Churchill Sumatra, hand-rolled Nicaraguan churchill with a Sumatra-shade wrapper, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Sumatra Shade Wrapper",
    price: "$40.00",
    quantity: 25,
    strength: 2,
    strengthLabel: "Mild &ndash; Medium",
    desc: "Seven inches of unhurried elegance: our classic Churchill draped in the same Sumatra-shade leaf as its robusto sibling. A long, cool burn with a gentle natural sweetness that deepens through the final third.",
    ogImage: "/assets/images/premium-churchill-sumatra.jpg",
    images: [
      { src: "/assets/images/premium-churchill-sumatra.webp", alt: "Churchill Sumatra: single cigar over the Pita spec card scene", width: 720, height: 960 },
      { src: "/assets/images/premium-churchill-sumatra-bundle.webp", alt: "Churchill Sumatra bundle of 25 with a single cigar resting against it", width: 599, height: 886 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Churchill &middot; 7&quot; x 48" },
      { label: "Quantity", value: "25 per Bundle" },
      { label: "Wrapper", value: "Sumatra Shade" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute;)" },
    ],
    notes: ["Sweet Spice", "Cedar", "Toasted Nuts", "Earth", "Coffee"],
    story: [
      "The Churchill Sumatra stretches our Sumatra-shade blend to its most generous format: seven inches by a 48 ring gauge, rolled for the longest evening of the line.",
      "The slender ring focuses the wrapper&rsquo;s sweet spice while the length lets the aged Nicaraguan core unfold slowly, cream and cedar early, leather and coffee as the hour stretches on.",
    ],
    related: ["robusto-sumatra", "torpedo-habano"],
  },
  {
    slug: "churchill-indonesian",
    name: "Churchill Oscuro",
    title: "Churchill Oscuro | Pita Cigars",
    description: "Churchill Oscuro, hand-rolled Nicaraguan churchill with a dark Indonesian wrapper, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Indonesian Wrapper",
    price: "$40.00",
    quantity: 25,
    strength: 3,
    strengthLabel: "Medium",
    desc: "Hand-rolled in Nicaragua with an aged Nicaraguan filler beneath a rich, dark Indonesian wrapper, the Churchill Oscuro gives its Sumatra sibling a deeper, more distinct character. Rolled to the full seven-inch Churchill format, it delivers deep earth, dark cocoa, and a long, rounded, medium-bodied smoke.",
    ogImage: "/assets/images/premium-churchill-indonesian.jpg",
    images: [
      { src: "/assets/images/premium-churchill-indonesian.webp", alt: "Churchill Oscuro spec card: Nicaraguan filler and binder, Indonesian shade wrapper, vitola 7 x 48", width: 720, height: 1280 },
      { src: "/assets/images/premium-churchill-indonesian-bundle.webp", alt: "Churchill Oscuro bundle with a single cigar resting against it", width: 768, height: 1024 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Churchill &middot; 7&quot; x 48" },
      { label: "Quantity", value: "25 per Bundle" },
      { label: "Wrapper", value: "Indonesian" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute;)" },
    ],
    notes: ["Earth", "Dark Cocoa", "Oak", "Molasses", "Black Pepper"],
    story: [
      "The Churchill Oscuro drapes our Nicaraguan long-filler in an Indonesian-grown wrapper, a darker, oilier leaf that trades the Sumatra&rsquo;s sweetness for depth, rolled to the longest format in the line.",
      "Expect a fuller, earthier smoke with notes of dark cocoa and seasoned oak, balanced so the strength builds gently rather than announcing itself. Seven unhurried inches give that depth room to unfold.",
    ],
    related: ["robusto-sumatra", "churchill-sumatra"],
  },
  {
    slug: "toro-habano",
    name: "Toro aka 52 Regular",
    title: "Toro aka 52 Regular | Pita Cigars",
    description: "Toro aka 52 Regular, hand-rolled Nicaraguan cigar with a rich Indonesian wrapper, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Indonesian Wrapper",
    price: "$40.00",
    quantity: 25,
    strength: 3,
    strengthLabel: "Medium",
    desc: "The 52 Regular pairs our aged Nicaraguan filler with a rich, dark Indonesian wrapper. Generously sized and cool-burning, it unfolds a complex, robust profile of warm spice and earthy depth over oak and dark cocoa. Superior construction, remarkable value.",
    ogImage: "/assets/images/premium-toro-habano.jpg",
    images: [
      { src: "/assets/images/premium-toro-habano.webp", alt: "52 Regular spec card: Nicaraguan filler and binder, Indonesian Shade wrapper, vitola 6 x 52", width: 768, height: 1360 },
      { src: "/assets/images/premium-toro-habano-lifestyle.webp", alt: "52 Regular bundle banded 6 x 52, with a single cigar standing forward", width: 832, height: 1248 },
    ],
    specs: [
      { label: "Factory &amp; Blender", value: "Pita Cigars" },
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Vitola", value: "Toro &middot; 6&quot; x 52" },
      { label: "Quantity", value: "25 per Bundle" },
      { label: "Wrapper", value: "Indonesian" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute;)" },
    ],
    notes: ["Earth", "Dark Cocoa", "Oak", "Black Pepper", "Baking Spice"],
    story: [
      "The 52 Regular is a straight, generously sized toro finished in a rich, dark wrapper grown in Indonesia.",
      "Its aged Nicaraguan filler gives a medium body with remarkable complexity: earth and warm baking spice woven through a foundation of oak and dark cocoa. A cigar meant to be savored without occasion.",
    ],
    related: ["torpedo-habano", "robusto-indonesian"],
  },
];
