module.exports = [
  {
    slug: "torpedo-habano",
    name: "Torpedo Habano",
    title: "Torpedo Habano | Pita Cigars",
    description: "Torpedo Habano, hand-rolled Nicaraguan Habano cigar, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Nicaraguan Habano",
    price: "$40.00",
    strength: 4,
    strengthLabel: "Full",
    desc: "A bold, full-bodied torpedo finished with a dark, oily Nicaraguan Habano wrapper. Its tapered head concentrates the smoke for a rich, focused draw, layered notes of espresso and cocoa over a foundation of pepper and aged cedar. A Nicaraguan puro built for the seasoned palate.",
    cardFrameClass: "product-card__frame--torpedo",
    images: [
      { src: "/assets/images/premium-torpedo-habano.jpg", alt: "Torpedo Habano bundle tied with twine", width: 832, height: 832 },
    ],
    specs: [
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Wrapper", value: "Nicaraguan Habano" },
      { label: "Binder", value: "Nicaraguan (Jalapa)" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Condega)" },
      { label: "Vitola", value: "Torpedo" },
      { label: "Length", value: '6.1"' },
      { label: "Ring Gauge", value: "52" },
      { label: "Strength", value: "Full" },
    ],
    notes: ["Espresso", "Dark Cocoa", "Black Pepper", "Cedar", "Leather"],
    story: [
      "The Torpedo Habano earns its name from the figurado shape our rollers hand-form leaf by leaf, a tapered head that concentrates the aromas of a sun-grown Habano wrapper into every draw.",
      "Wrapper, binder, and filler are all grown in the volcanic soil of Est&eacute;l&iacute;, making this a true Nicaraguan puro. Slow-fermented and patiently aged, it delivers depth and power without ever losing its balance.",
    ],
    related: ["torpedo-connecticut", "toro-habano"],
  },
  {
    slug: "torpedo-connecticut",
    name: "Torpedo Connecticut",
    title: "Torpedo Connecticut | Pita Cigars",
    description: "Torpedo Connecticut, hand-rolled Nicaraguan Connecticut cigar, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Connecticut Shade Wrapper",
    price: "$40.00",
    strength: 2,
    strengthLabel: "Mild &ndash; Medium",
    desc: "An elegant, approachable torpedo wrapped in a silky golden Connecticut-shade leaf. Smooth and creamy with a gentle sweetness and a tapered head that sharpens every note, the perfect morning cigar and an ideal introduction to the Pita house style.",
    images: [
      { src: "/assets/images/premium-torpedo-connecticut.jpg", alt: "Torpedo Connecticut: single cigar with a bundle in the background", width: 720, height: 960 },
    ],
    specs: [
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Wrapper", value: "Connecticut Shade" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Jalapa)" },
      { label: "Vitola", value: "Torpedo" },
      { label: "Length", value: '6"' },
      { label: "Ring Gauge", value: "52" },
      { label: "Strength", value: "Mild &ndash; Medium" },
    ],
    notes: ["Cream", "Cedar", "Almond", "Sweet Hay", "White Pepper"],
    story: [
      "The Torpedo Connecticut pairs our signature figurado shape with a shade-grown Connecticut wrapper, prized for its supple texture and naturally sweet, understated flavor.",
      "Beneath that golden leaf sits a core of aged Nicaraguan long-filler, hand-bunched to burn slow and cool. Refined without being timid, it proves a milder cigar need never be a lesser one.",
    ],
    related: ["torpedo-habano", "robusto-sumatra"],
  },
  {
    slug: "robusto-sumatra",
    name: "Robusto Sumatra",
    title: "Robusto Sumatra | Pita Cigars",
    description: "Robusto Sumatra, hand-rolled Nicaraguan robusto with a Sumatra-shade wrapper, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Sumatra Shade Wrapper",
    price: "$40.00",
    strength: 2,
    strengthLabel: "Mild &ndash; Medium",
    desc: "A stout, slow-burning robusto dressed in a genuine Sumatra-shade wrapper, subtly sweet, gently spiced, and effortlessly smooth. The same aged Nicaraguan long-filler as our torpedoes in a shorter format, built for the everyday hour.",
    images: [
      { src: "/assets/images/premium-robusto-sumatra.jpg", alt: "Robusto Sumatra: single cigar with a bundle in the background", width: 720, height: 960 },
      { src: "/assets/images/premium-robusto-sumatra-bundle.jpg", alt: "Robusto Sumatra bundle of 25 with a single cigar resting against it", width: 768, height: 1024 },
    ],
    specs: [
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Wrapper", value: "Sumatra Shade" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Jalapa)" },
      { label: "Vitola", value: "Robusto" },
      { label: "Length", value: '5"' },
      { label: "Ring Gauge", value: "52" },
      { label: "Strength", value: "Mild &ndash; Medium" },
    ],
    notes: ["Sweet Spice", "Cedar", "Toasted Bread", "Raisin", "Coffee"],
    story: [
      "The Robusto Sumatra pairs our aged Nicaraguan core with a Sumatra-seed wrapper leaf prized for its restrained natural sweetness and delicate spice.",
      "At five inches with a 52 ring gauge, it is the most companionable cigar we make: forty-five unhurried minutes of sweet earth, cedar, and soft baking spice that never asks more of you than it gives.",
    ],
    related: ["robusto-indonesian", "torpedo-habano"],
  },
  {
    slug: "robusto-indonesian",
    name: "Robusto Indonesian",
    title: "Robusto Indonesian | Pita Cigars",
    description: "Robusto Indonesian, hand-rolled Nicaraguan robusto with a dark Indonesian wrapper, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Indonesian Wrapper",
    price: "$40.00",
    strength: 3,
    strengthLabel: "Medium",
    desc: "The Robusto Sumatra&rsquo;s darker sibling, a rich Indonesian-grown wrapper laid over the same aged Nicaraguan long-filler core. Deeper earth, dark cocoa, and a rounded, medium-bodied finish from the first draw to the last.",
    images: [
      { src: "/assets/images/premium-robusto-indonesian.jpg", alt: "Robusto Indonesian bundle with a single cigar resting against it", width: 768, height: 1024 },
    ],
    specs: [
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Wrapper", value: "Indonesian" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Jalapa)" },
      { label: "Vitola", value: "Robusto" },
      { label: "Length", value: '5"' },
      { label: "Ring Gauge", value: "52" },
      { label: "Strength", value: "Medium" },
    ],
    notes: ["Earth", "Dark Cocoa", "Oak", "Molasses", "Black Pepper"],
    story: [
      "The Robusto Indonesian drapes our Nicaraguan long-filler in an Indonesian-grown wrapper, a darker, oilier leaf that trades the Sumatra&rsquo;s sweetness for depth.",
      "Expect a fuller, earthier smoke with notes of dark cocoa and seasoned oak, balanced so the strength builds gently rather than announcing itself. The same blend beneath, an entirely different evening.",
    ],
    related: ["robusto-sumatra", "toro-habano"],
  },
  {
    slug: "churchill-sumatra",
    name: "Churchill Sumatra",
    title: "Churchill Sumatra | Pita Cigars",
    description: "Churchill Sumatra, hand-rolled Nicaraguan churchill with a Sumatra-shade wrapper, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Sumatra Shade Wrapper",
    price: "$40.00",
    strength: 2,
    strengthLabel: "Mild &ndash; Medium",
    desc: "Seven inches of unhurried elegance: our classic Churchill draped in the same Sumatra-shade leaf as its robusto sibling. A long, cool burn with a gentle natural sweetness that deepens through the final third.",
    images: [
      { src: "/assets/images/premium-churchill-sumatra.jpg", alt: "Churchill Sumatra: single cigar over the Pita spec card scene", width: 720, height: 960 },
      { src: "/assets/images/premium-churchill-sumatra-bundle.jpg", alt: "Churchill Sumatra bundle of 25 with a single cigar resting against it", width: 599, height: 886 },
    ],
    specs: [
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Wrapper", value: "Sumatra Shade" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Jalapa)" },
      { label: "Vitola", value: "Churchill" },
      { label: "Length", value: '7"' },
      { label: "Ring Gauge", value: "48" },
      { label: "Strength", value: "Mild &ndash; Medium" },
    ],
    notes: ["Sweet Spice", "Cedar", "Cream", "Leather", "Coffee"],
    story: [
      "The Churchill Sumatra stretches our Sumatra-shade blend to its most generous format: seven inches by a 48 ring gauge, rolled for the longest evening of the line.",
      "The slender ring focuses the wrapper&rsquo;s sweet spice while the length lets the aged Nicaraguan core unfold slowly, cream and cedar early, leather and coffee as the hour stretches on.",
    ],
    related: ["robusto-sumatra", "torpedo-habano"],
  },
  {
    slug: "churchill-indonesian",
    name: "Churchill Indonesian",
    title: "Churchill Indonesian | Pita Cigars",
    description: "Churchill Indonesian, hand-rolled Nicaraguan churchill with a dark Indonesian wrapper, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Indonesian Wrapper",
    price: "$40.00",
    strength: 3,
    strengthLabel: "Medium",
    desc: "The Churchill Sumatra&rsquo;s darker sibling, a rich Indonesian-grown wrapper laid over the same aged Nicaraguan long-filler core, rolled to the full seven-inch Churchill format. Deeper earth, dark cocoa, and a long, rounded, medium-bodied smoke.",
    images: [
      { src: "/assets/images/premium-churchill-indonesian.jpg", alt: "Churchill Indonesian bundle with a single cigar resting against it", width: 768, height: 1024 },
    ],
    specs: [
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Wrapper", value: "Indonesian" },
      { label: "Binder", value: "Nicaraguan" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Jalapa)" },
      { label: "Vitola", value: "Churchill" },
      { label: "Length", value: '7"' },
      { label: "Ring Gauge", value: "48" },
      { label: "Strength", value: "Medium" },
    ],
    notes: ["Earth", "Dark Cocoa", "Oak", "Molasses", "Black Pepper"],
    story: [
      "The Churchill Indonesian drapes our Nicaraguan long-filler in an Indonesian-grown wrapper, a darker, oilier leaf that trades the Sumatra&rsquo;s sweetness for depth, rolled to the longest format in the line.",
      "Expect a fuller, earthier smoke with notes of dark cocoa and seasoned oak, balanced so the strength builds gently rather than announcing itself. Seven unhurried inches give that depth room to unfold.",
    ],
    related: ["robusto-sumatra", "churchill-sumatra"],
  },
  {
    slug: "toro-habano",
    name: "Toro Habano",
    title: "Toro Habano | Pita Cigars",
    description: "Toro Habano, hand-rolled Nicaraguan Habano cigar, made in Esteli, Nicaragua by Pita Cigars.",
    blend: "Nicaraguan Habano",
    price: "$40.00",
    strength: 3,
    strengthLabel: "Medium",
    desc: "A classic medium-bodied toro beneath a rich Nicaraguan Habano wrapper. Its generous ring gauge burns cool and even, unfolding notes of dried fruit and warm baking spice over oak and cocoa. Balanced, complex, and endlessly smokable.",
    images: [
      { src: "/assets/images/premium-toro-habano.jpg", alt: "Toro Habano cigar", width: 900, height: 1200 },
    ],
    specs: [
      { label: "Origin", value: "Est&eacute;l&iacute;, Nicaragua" },
      { label: "Wrapper", value: "Nicaraguan Habano" },
      { label: "Binder", value: "Nicaraguan (Condega)" },
      { label: "Filler", value: "Nicaraguan (Est&eacute;l&iacute; &amp; Jalapa)" },
      { label: "Vitola", value: "Toro" },
      { label: "Length", value: '6"' },
      { label: "Ring Gauge", value: "52" },
      { label: "Strength", value: "Medium" },
    ],
    notes: ["Dried Fruit", "Cinnamon", "Oak", "Cocoa", "Baking Spice"],
    story: [
      "The Toro Habano is the everyday favorite of the Pita range, a straight, generously sized toro under a sun-grown Habano wrapper grown in the fields of Est&eacute;l&iacute;.",
      "Its aged Nicaraguan filler gives a medium body with remarkable complexity: dried fruit and cinnamon woven through a foundation of oak and cocoa. A cigar meant to be savored without occasion.",
    ],
    related: ["torpedo-habano", "robusto-indonesian"],
  },
];
